author: Sean Hammond
title: seanh.cc
remote_theme: seanh/jekyll-theme-oatcake@0.1.17
github_ribbon: true
permalink: pretty
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-avatar
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
relative_links:
  enabled:     true
  collections: true
social:
  name: Sean Hammond
  links:
    - https://twitter.com/snhmnd
    - https://www.linkedin.com/in/sean-hammond-412b8425/
    - https://github.com/seanh
    - https://keybase.io/seanh
lang: en_GB
titles_from_headings:
  strip_title: true
  collections: true
